# IONetFamily - network stack objects for the XKERN build.
IONET_OBJS = iokit/IONetFamily/ionet.o \
             iokit/IONetFamily/ether.o \
             iokit/IONetFamily/arp.o \
             iokit/IONetFamily/ipv4.o \
             iokit/IONetFamily/icmp.o \
             iokit/IONetFamily/udp.o \
             iokit/IONetFamily/dhcp.o \
             iokit/IONetFamily/e1000.o
