#this is ext3 fs for xkern

BUILD_ID = 30.8.26_xkern

EXT3_OBJS = bsd/ext3/src/disk.o \
            bsd/ext3/src/superblock.o \
            bsd/ext3/src/blk_group.o \
            bsd/ext3/src/inode.o \
            bsd/ext3/src/dir.o \
            bsd/ext3/src/fs.o
