#!/bin/sh
#
# gen_payload.sh - regenerate the embedded install-payload assembly stub.
#
# If install.img exists (a bootable isohybrid XKERN image produced by
# scripts/build_full_iso.sh), install_payload.S .incbin's it into the
# kernel's .install_payload section.  If it does not exist yet, an empty
# stub is emitted so the plain kernel builds standalone (first pass).
#
# Output: devkits/gpukit/payload/install_payload.S

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IMG="$ROOT/install.img"
OUT="$ROOT/devkits/gpukit/payload/install_payload.S"

mkdir -p "$(dirname "$OUT")"

{
    echo "# generated by scripts/gen_payload.sh -- do not edit"
    echo ".section .install_payload"
    echo ".global install_payload_start"
    echo ".global install_payload_end"
    echo "install_payload_start:"
    if [ -s "$IMG" ]; then
        echo ".incbin \"install.img\""
    fi
    echo "install_payload_end:"
    echo ".section .note.GNU-stack,\"\",@progbits"
} > "$OUT"

echo "gen_payload: $(basename "$OUT") $([ -s "$IMG" ] && echo "(embeds install.img, $(wc -c < "$IMG") bytes)" || echo "(empty: no install.img yet)")"
