#!/bin/sh

OUT="osfmk/kern/version.c"

YEAR="$(date '+%Y')"
MAJOR="26"
MINOR="2"
REV="9"

VERSION="$MAJOR.$MINOR.$REV"
DATE="$(date '+%a %b %d %Y')"
COMPILED="$(uname -srm)"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
/*
    kernel version globals
    autogenerated by version_maker.sh
*/
#include "types.h"

const char version[]   = "xkern Kernel Version $VERSION: $DATE; root:xkern_${VERSION}~1/TEST_x86_64:from $COMPILED";
const char ostype[]    = "xkern";
const char osrelease[] = "$VERSION";
const char arch[]      = "x64_intel/amd";
const int osrelease_major = $MAJOR;
const int osrelease_minor = $MINOR;
const int osrelease_rev   = $REV;
const char lang[] = "c,cpp";
/*
    Version format:
      major = year - 2000
      minor = day of month
      rev   = month number
*/
EOF
