INITRAM_OBJS = bsd/kern/init_ram_getty/init.o \
               bsd/kern/init_ram_getty/script.o \
               bsd/kern/init_ram_getty/valid.o \
               bsd/kern/init_ram_getty/proc.o \
               bsd/kern/init_ram_getty/syscall.o \
               bsd/kern/init_ram_getty/fs.o
